---
Blackbox_serviceName: "blackbox_exporter"
exec_command: /usr/local/bin/blackbox_exporter --config.file /etc/blackbox_exporter/blackbox.yml
blackbox_exporter_bin: /usr/local/bin/blackbox_exporter
black_exporter_user: blackbox_exporter
blackbox_exporter_group: "{{ blackbox_exporter_user }}"
blackbox_exporter_version: 0.25.0
blackbox_exporter_dir_conf: /etc/node_exporter