---
- name: install gpg
  apt:  #apt module manages apt packages such as for debian/ubuntu
    name: gnupg,software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 3600
- name: add gpg hey
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no
- name: add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no
- name: install grafana
  apt:
    name: grafana
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
- name: wait for service up
  uri:
    url: "http://localhost:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1
  
- name: change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0

# - name: import Grafana Dashboards
#   community.grafana.grafana_dashboard:
#     # grafana_url: http://grafana.sara.ddev.sg:3000
#     url: "{{ grafana_url }}"
#     folder: "{{ title }} MACH"
#     dashboard_id: "{{ item }}"
#     overwrite: true
#     url_password: "Password1234"
#   loop: "{{ grafana_dashboard_ids }}"
#   notify:
#     - Restart grafana-server
#   when: enable_grafana_import and ( inventory_hostname on groups['grafana'])