# prometheus_dir_configuration: "/etc/prometheus"
# prometheus_retention_time: "30d"
# prometheus_scrape_interval: "30s"
# prometheus_node_exporter: true
# prometheus_node_exporter_group: "all"
# prometheus_env: "production"
# prometheus_var_config:
#   global:
#     scrape_interval: "{{ prometheus_scrape_interval }}"
#     evaluation_interval: 5s
#     external_labels:
#       env: '{{ prometheus_env }}'
#   scrape_configs:
#     - job_name: prometheus
#       scrape_interval: 5m
#       static_configs:
#         - targets: ['{{ inventory_hostname }}:9090']



# - name: Install Prometheus
#   hosts: all
#   become: yes
#   tasks:

#     # Install necessary dependencies
#     - name: Install required packages
#       apt:
#         name:
#           - wget
#           - tar
#           - systemd
#         state: present
#         update_cache: yes

#     # Download Prometheus tarball
#     - name: Download Prometheus tarball
#       get_url:
#         url: "https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
#         dest: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"

#     # Extract the tarball
#     - name: Extract Prometheus tarball
#       unarchive:
#         src: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"
#         dest: "/opt"
#         remote_src: yes

#     # Create Prometheus user and group
#     - name: Create prometheus user and group
#       user:
#         name: prometheus
#         shell: /bin/false
#         system: yes

#     # Create necessary directories for Prometheus
#     - name: Create Prometheus directories
#       file:
#         path: "{{ item }}"
#         state: directory
#         owner: prometheus
#         group: prometheus
#         mode: '0755'
#       loop:
#         - /etc/prometheus
#         - /var/lib/prometheus

#     # Move binaries to /usr/local/bin
#     - name: Move Prometheus binaries to /usr/local/bin
#       command: mv /opt/prometheus-2.45.0.linux-amd64/{{ item }} /usr/local/bin/
#       with_items:
#         - prometheus
#         - promtool

#     # Move configuration and other files to /etc/prometheus
#     - name: Move Prometheus configuration files
#       copy:
#         src: "/opt/prometheus-2.45.0.linux-amd64/{{ item }}"
#         dest: "/etc/prometheus/"
#         owner: prometheus
#         group: prometheus
#         mode: '0644'
#       with_items:
#         - prometheus.yml
#         - consoles
#         - console_libraries

#     # Create a systemd service file for Prometheus
#     - name: Create Prometheus systemd service file
#       copy:
#         dest: /etc/systemd/system/prometheus.service
#         content: |
#           [Unit]
#           Description=Prometheus
#           Documentation=https://prometheus.io/docs/introduction/overview/
#           After=network.target

#           [Service]
#           User=prometheus
#           Group=prometheus
#           Type=simple
#           ExecStart=/usr/local/bin/prometheus \
#             --config.file=/etc/prometheus/prometheus.yml \
#             --storage.tsdb.path=/var/lib/prometheus/ \
#             --web.console.templates=/etc/prometheus/consoles \
#             --web.console.libraries=/etc/prometheus/console_libraries

#           [Install]
#           WantedBy=multi-user.target
#         owner: root
#         group: root
#         mode: '0644'

#     # Reload systemd to apply the service file
#     - name: Reload systemd
#       systemd:
#         daemon_reload: yes

#     # Start and enable the Prometheus service
#     - name: Start Prometheus service
#       systemd:
#         name: prometheus
#         state: started
#         enabled: yes

#     # Clean up temporary files
#     - name: Remove downloaded tarball
#       file:
#         path: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"
#         state: absent
