---
# - name: Creating prometheus user group
#   group: name="{{groupId}}"
#   become: true

# - name: Creating prometheus user
#   user:
#     name: "{{userId}}"
#     group: "{{groupId}}"
#     system: yes
#     shell: "/sbin/nologin"
#     comment: "{{userId}} nologin User"
#     createhome: "no"
#     state: present

##Install prometheus

# - name: download and unzip prometheus if not exist
#   unarchive:
#     src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
#     dest: /tmp/
#     remote_src: yes

# - name: Copy prometheus file to bin
#   copy:    #copy module copies a file from the local or remote machine to a location on the remote machine.
#     src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
#     dest: "/usr/local/bin/prometheus"
#     # owner: "{{userId}}"
#     # group: "{{groupId}}"
#     remote_src: yes
#     mode: 0755

# - name: Delete prometheus tmp folder
#   file:   #File module - It sets or remove attributes of files, symlinks, or directories.
#     path: '/tmp/prometheus-{{ prometheus_version }}.linux-amd64'
#     state: absent

# - name: Creates directory
#   file: 
#     path: "/data/prometheus/"
#     state: directory
#     # owner: "{{userId}}"
#     # group: "{{groupId}}"
#     mode: 0755

# - name: Creates directory
#   file: 
#     path: "/etc/prometheus/"
#     state: directory
#     # owner: "{{userId}}"
#     # group: "{{groupId}}"
#     mode: 0755

# - name: config file
#   template:
#     src: prometheus.yml.j2
#     dest: /etc/prometheus/prometheus.yml

# - name: alert config file
#   copy:
#     src: "{{ role_path }}/defaults/alertrules.yml"
#     dest: /etc/prometheus/alert.rules.yml

# - name: Copy systemd init file
#   template:
#     src: prometheus.service.j2
#     dest: /etc/systemd/system/prometheus.service
#   notify: restart_prometheus

# - name: Start prometheus service
#   service:  #service module enables you to start, stop, and reload installed packages
#     name: prometheus
#     state: started
#     enabled: yes

# - name: Check if prometheus is accessible
#   uri:
#     url: http://localhost:9090
#     method: GET
#     status_code: 200

# - name: Install Prometheus
#   hosts: all
#   become: yes
#   tasks:

    # Install necessary dependencies
- name: Install required packages
  apt:
    name:
      - wget
      - tar
      - systemd
    state: present
    update_cache: yes
  become: yes

    # Download Prometheus tarball
- name: Download Prometheus tarball
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.45.0/prometheus-2.45.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"

    # Extract the tarball
- name: Extract Prometheus tarball
  unarchive:
    src: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"
    dest: "/opt"
    remote_src: yes
  become: yes

    # Create Prometheus user and group
- name: Create prometheus user and group
  user:
    name: prometheus
    shell: /bin/false
    system: yes
  become: yes

    # Create necessary directories for Prometheus
- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "prometheus"
    group: "prometheus"
    mode: '0777'
  become: yes
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus
  
  
#     # Move binaries to /usr/local/bin
# - name: Move Prometheus binaries to /usr/local/bin
#   command: mv /opt/prometheus-2.45.0.linux-amd64/{{ item }} /usr/local/bin/
#   with_items:
#     - prometheus
#     - promtool
#   become: yes

    # Move configuration and other files to /etc/prometheus
- name: Move Prometheus configuration files
  copy:
    src: "/opt/prometheus-2.45.0.linux-amd64/{{ item }}"
    dest: "/etc/prometheus/"
    owner: prometheus
    group: prometheus
    mode: '0777'
    remote_src: yes
  with_items:
    - prometheus
    - consoles
    - console_libraries
    - promtool
    - prometheus.yml
  become: yes

- name: Copy my Config file
  template:
    src: prometheus2.yml.j2
    dest: /etc/prometheus/prometheus.yml

# - name: Ensure prometheus.yml has scrape interval and node_exporter job configuration
#   blockinfile:
#     path: "/etc/prometheus/prometheus.yml"
#     marker: "# BEGIN node_exporter configuration"
#     block: |
#       scrape_interval: 15s

#       external_labels:
#         monitor: 'prometheus'

#       scrape_configs:
#         - job_name: 'node_exporter'
#           static_configs:
#             - targets: ['10.46.1.100:9090']
#   become: yes

    # Create a systemd service file for Prometheus
- name: Create Prometheus systemd service file
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Documentation=https://prometheus.io/docs/introduction/overview/
      After=network.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/etc/prometheus/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus/ \
        --web.console.templates=/etc/prometheus/consoles \
        --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
  become: yes
      
    # Reload systemd to apply the service file
- name: Reload systemd
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted
    enabled: yes
  become: yes

    # Start and enable the Prometheus service
- name: Start Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: yes
  become: yes

    # Clean up temporary files
- name: Remove downloaded tarball
  file:
    path: "/tmp/prometheus-2.45.0.linux-amd64.tar.gz"
    state: absent
