---
- name: Enable grafana-server
  ansible.builtin.systemd_service:
    name: grafana-server
    daemon_reload: true
    state: started
  become: true

- name: Start grafana-server
  ansible.builtin.systemd_service:
    name: grafana-server
    state: started
  become: true

- name: Restart grafana-server
  ansible.builtin.systemd_service:
    name: grafana-server
    state: restarted
  become: true



# - name: "Restart the Grafana service."
#   service:
#     name: grafana-server
#     state: restarted
#   listen: event_restart_grafana